[package]
name = "hdf5-derive"
version = "0.2.0"
authors = ["Ivan Smirnov <i.s.smirnov@gmail.com>"]
edition = "2018"

[lib]
proc-macro = true

[features]
compiletest = ["compiletest_rs"]

[dependencies]
hdf5-types = { path = "../hdf5-types", version = "0.2.0" }
syn = "0.11"
quote = "0.3"
clippy = { version = "*", optional = true }
compiletest_rs = { version = "0.3", optional = true }
