version: 0.1.{build}-{branch}
platform:
  - x64
os: Visual Studio 2015
matrix:
  fast_finish: true
skip_tags: true
build: false

environment:
  TARGET: x86_64-pc-windows-msvc
  HDF5_BINDIR: "C:\\Program Files\\HDF_Group\\HDF5\\1.8.17\\bin"
  HDF5_URL: "https://support.hdfgroup.org/ftp/HDF5/prev-releases/hdf5-1.8.17/bin/windows/extra/hdf5-1.8.17-win64-vs2015-shared.zip"
  matrix:
    - CHANNEL: 1.15.0
      FEATURES: ""
    - CHANNEL: beta
      FEATURES: ""
    - CHANNEL: nightly
      FEATURES: "clippy"
install:
  - ps: Start-FileDownload "https://static.rust-lang.org/dist/rust-${env:CHANNEL}-${env:TARGET}.msi"
  - ps: Start-Process -FilePath msiexec -ArgumentList /i, rust-${env:CHANNEL}-${env:TARGET}.msi, INSTALLDIR="C:\Rust", /quiet -Wait
  - set PATH=%PATH%;C:\Rust\bin;%HDF5_BINDIR%
  - rustc -vV
  - cargo -vV
  - ps: Invoke-WebRequest ${env:HDF5_URL} -OutFile hdf5.zip
  - 7z x hdf5.zip -y
  - ps: Start-Process -FilePath msiexec -ArgumentList /i, "hdf5\HDF5-1.8.17-win64.msi", /quiet -Wait

test_script:
  - cd %APPVEYOR_BUILD_FOLDER%\libhdf5-lib
  - cargo test -v --no-run
  - cargo test -v
  - cd %APPVEYOR_BUILD_FOLDER%\libhdf5-sys
  - cargo test -v --no-run
  - cargo test -v
  - cd %APPVEYOR_BUILD_FOLDER%
  - cargo test -v --no-run --features "%FEATURES%"
  - cargo test -v --features "%FEATURES%"
