# appveyor.yml
# 
# vim: sw=4 ts=4 et
#
environment:
    RUST_TARGET: x86_64-pc-windows-gnu
    HDF5_LIBDIR: C:\hdf5_bin

install:
    # get rust & cargo
    - ps: Start-FileDownload "https://static.rust-lang.org/dist/rust-1.1.0-${env:RUST_TARGET}.exe"
    - rustc-1.1.0-%RUST_TARGET%.exe /VERYSILENT /NORESTART /DIR="C:\Program Files\Rust"

    - set PATH=%PATH%;C:\Program Files\Rust\bin

    # output version info
    - rustc --version
    - cargo --version

build: false

