[package]
name = "hdf5-rs"
version = "0.1.1"
authors = ["Ivan Smirnov <i.s.smirnov@gmail.com>"]
keywords = ["hdf5"]
license = "MIT/Apache-2.0"
readme = "README.md"
description = "Thread-safe Rust bindings for the HDF5 library."
repository = "https://github.com/aldanor/hdf5-rs"
homepage = "https://github.com/aldanor/hdf5-rs"
exclude = [
    "appveyor.yml",
    ".travis.yml",
    ".gitignore"
]

[features]
unstable = ["clippy"]

[dependencies]
lazy_static = "0.1"
num = "0.1"
libc = "0.2"
libhdf5-sys = { path = "libhdf5-sys", version = "0.1.1" }
remutex = { path = "remutex", version = "0.1.1" }
clippy = { version = "^0.0.63", optional = true }

[dev-dependencies]
regex = "0.1"
tempdir = "0.3"
