[package]
name = "hdf5-types-derive"
version = "0.2.0"
authors = ["Ivan Smirnov <i.s.smirnov@gmail.com>"]

[lib]
proc-macro = true

[dependencies]
hdf5-types = { path = "../hdf5-types", version = "0.2.0" }
syn = "0.11"
quote = "0.3"
