[package]
name = "hdf5-types"
version = "0.2.0"
authors = ["Ivan Smirnov <i.s.smirnov@gmail.com>"]

[dependencies]
ascii = "0.8"
libc = "0.2"
clippy = { version = "*", optional = true }

[dev-dependencies]
quickcheck = "0.4"

[dependencies.error-chain]
version = "0.10"
default-features = false
