[package]
name = "hdf5-types"
version = "0.6.0"  # !V
authors = ["Ivan Smirnov <i.s.smirnov@gmail.com>"]
keywords = ["hdf5"]
license = "MIT/Apache-2.0"
description = "Native Rust equivalents of HDF5 types."
repository = "https://github.com/aldanor/hdf5-rust"
homepage = "https://github.com/aldanor/hdf5-rust"
edition = "2018"

[dependencies]
ascii = "0.9"
libc = "0.2"

[dev-dependencies]
quickcheck = "0.8"
