[package]
name = "hdf5-types"
version = "0.2.0"
authors = ["Ivan Smirnov <i.s.smirnov@gmail.com>"]
edition = "2018"

[dependencies]
ascii = "0.9"
libc = "0.2"

[dev-dependencies]
quickcheck = "0.8"

[dependencies.error-chain]
version = "0.12"
default-features = false
